### PR TITLE
4th commit: bad commit

### PR DESCRIPTION
**Pull request by nguyenhuulong**
This is my 4th commit. **It's a bad commit ..**

---
This change is [Reviewable](https://reviewable.io/reviews/nguyenhuulongpr/vedo/3)

### CODE REVIEW

**Comment by nguyenhuulongpr** [comment]
Okay. It should be a bad commit ..

**Comment by nguyenhuulongpr** [comment]
*[`backend/app.py` line 28 at r1](https://reviewable.io/reviews/nguyenhuulongpr/vedo/3#-N0amKWk6kOsffYFU4L-:-N0amKWk6kOsffYFU4L0:b84b4u5) ([raw file](https://github.com/nguyenhuulongpr/vedo/blob/b18e9dec83c263e83ef42f0690cbe811ac1d203f/backend/app.py#L28)):*
> ```Python
>         img_path = 'input.jpeg'
>         result = ocr.ocr(img_path)
>         res = "  "
> ```

What is this blank? This will ruin the result when you call your APIs.

**Review by nguyenhuulongpr — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/nguyenhuulongpr/vedo/3)* status: all files reviewed, 1 unresolved discussion (waiting on @nguyenhuulong)

**Comment by nguyenhuulong** [comment]
*[`backend/app.py` line 28 at r1](https://reviewable.io/reviews/nguyenhuulongpr/vedo/3#-N0amKWk6kOsffYFU4L-:-N0an0M_1bX3TFnnm-KU:b-9fqdpp) ([raw file](https://github.com/nguyenhuulongpr/vedo/blob/b18e9dec83c263e83ef42f0690cbe811ac1d203f/backend/app.py#L28)):*
<details><summary><i>Previously, nguyenhuulongpr wrote…</i></summary><blockquote>

What is this blank? This will ruin the result when you call your APIs.
</blockquote></details>

I'm sorry. I'll fix it in the next commit.

**Review by nguyenhuulongpr — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/nguyenhuulongpr/vedo/3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nguyenhuulong)

**Review by nguyenhuulongpr — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/nguyenhuulongpr/vedo/3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nguyenhuulong)

**Pull request merged**
