### PR TITLE
5th commit: commit to be denied

### PR DESCRIPTION
**Pull request by nguyenhuulong**
Deny it please

---
This change is [Reviewable](https://reviewable.io/reviews/nguyenhuulongpr/vedo/5)

### CODE REVIEW

**Comment by nguyenhuulongpr** [comment]
*[`backend/app.py` line 29 at r1](https://reviewable.io/reviews/nguyenhuulongpr/vedo/5#-N0apUYv03HEWnxeOvWU:-N0apUYv03HEWnxeOvWV:bp4nahh) ([raw file](https://github.com/nguyenhuulongpr/vedo/blob/62ce7d9dbe9e2c1ebfac0978cc8736ff57d1dc3d/backend/app.py#L29)):*
> ```Python
>         result = ocr.ocr(img_path)
>         res = ""
>         # a really bad comment
> ```

It's terrified bro

**Review by nguyenhuulongpr — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/nguyenhuulongpr/vedo/5)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @nguyenhuulong and @nguyenhuulongpr)

**Review by nguyenhuulongpr — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/nguyenhuulongpr/vedo/5)* status: all files reviewed, 1 unresolved discussion (waiting on @nguyenhuulong)

**Comment by nguyenhuulongpr** [comment]
*[`backend/app.py` line 29 at r1](https://reviewable.io/reviews/nguyenhuulongpr/vedo/5#-N0apUYv03HEWnxeOvWU:-N0apocQBAN6v6nIABfS:b-4rwbux) ([raw file](https://github.com/nguyenhuulongpr/vedo/blob/62ce7d9dbe9e2c1ebfac0978cc8736ff57d1dc3d/backend/app.py#L29)):*
<details><summary><i>Previously, nguyenhuulongpr wrote…</i></summary><blockquote>

It's terrified bro
</blockquote></details>

I cannot merge it. Sorry

**Comment by nguyenhuulong** [comment]
*[`backend/app.py` line 29 at r1](https://reviewable.io/reviews/nguyenhuulongpr/vedo/5#-N0apUYv03HEWnxeOvWU:-N0aq2JO0I8zU72WeLli:be4aw47) ([raw file](https://github.com/nguyenhuulongpr/vedo/blob/62ce7d9dbe9e2c1ebfac0978cc8736ff57d1dc3d/backend/app.py#L29)):*
<details><summary><i>Previously, nguyenhuulongpr wrote…</i></summary><blockquote>

I cannot merge it. Sorry
</blockquote></details>

It couldn't help :(

**Pull request closed without merging**
