### PR TITLE
3rd commit

### PR DESCRIPTION
**Pull request by nguyenhuulong**
This is my 3rd commit. I've added some changes to the app.py file. You should review it.

---
This change is [Reviewable](https://reviewable.io/reviews/nguyenhuulongpr/vedo/2)

### CODE REVIEW

**Comment by nguyenhuulongpr** [comment]
:lgtm:

**Comment by nguyenhuulongpr** [comment]
*[`backend/app.py` line 21 at r1](https://reviewable.io/reviews/nguyenhuulongpr/vedo/2#-N0akzQn7kcURGWTAynR:-N0akzQn7kcURGWTAynS:b-to731q) ([raw file](https://github.com/nguyenhuulongpr/vedo/blob/ff953a7726223f004f82239cb1da203ef3050012/backend/app.py#L21)):*
> ```Python
>     if request.method == 'POST':
>         data = request.get_json()
>         # example of an unclear comment
> ```

Your comment is unclear. You should delete it and move it to another file.

**Review by nguyenhuulongpr — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/nguyenhuulongpr/vedo/2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nguyenhuulong)

**Comment by nguyenhuulong** [comment]
:lgtm:

**Pull request merged**
