### PR TITLE
second commit

### PR DESCRIPTION
**Pull request by nguyenhuulong**
This is my second commit. I've added an example of a change line.

---
This change is [Reviewable](https://reviewable.io/reviews/nguyenhuulongpr/vedo/1)

### CODE REVIEW

**Comment by nguyenhuulongpr** [comment]
Okay I'll check it.

**Comment by nguyenhuulongpr** [comment]
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/nguyenhuulongpr/vedo/1#-N0aifso90nZXsYbtdi2):*
You should number it. Ex: 2nd

**Comment by nguyenhuulongpr** [comment]
*[`backend/app.py` line 34 at r1](https://reviewable.io/reviews/nguyenhuulongpr/vedo/1#-N0aimNaBUxhHAVFf45p:-N0aimNaBUxhHAVFf45q:bqvyipg) ([raw file](https://github.com/nguyenhuulongpr/vedo/blob/8d723b698c37886eed2d081e4efee7a61af6547d/backend/app.py#L34)):*
> ```Python
> 
> # example of CLs
> ```

This is a clear comment. Goodjob.

**Review by nguyenhuulongpr — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/nguyenhuulongpr/vedo/1)* status: all files reviewed, 2 unresolved discussions (waiting on @nguyenhuulong)

**Review by nguyenhuulongpr — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/nguyenhuulongpr/vedo/1#-:-N0aiurc9vT1GRrE7btr:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @nguyenhuulong)

**Comment by nguyenhuulong** [comment]
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/nguyenhuulongpr/vedo/1#-N0aifso90nZXsYbtdi2):*
<details><summary><i>Previously, nguyenhuulongpr wrote…</i></summary><blockquote>

You should number it. Ex: 2nd
</blockquote></details>

Done.

**Comment by nguyenhuulong** [comment]
*[`backend/app.py` line 34 at r1](https://reviewable.io/reviews/nguyenhuulongpr/vedo/1#-N0aimNaBUxhHAVFf45p:-N0aj7SU31sKt0-UEOj3:b-896fix) ([raw file](https://github.com/nguyenhuulongpr/vedo/blob/8d723b698c37886eed2d081e4efee7a61af6547d/backend/app.py#L34)):*
<details><summary><i>Previously, nguyenhuulongpr wrote…</i></summary><blockquote>

This is a clear comment. Goodjob.
</blockquote></details>

Done.

**Comment by nguyenhuulong** [comment]
:lgtm:

**Review by nguyenhuulongpr — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/nguyenhuulongpr/vedo/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nguyenhuulong)

**Pull request merged**
